sudo: required

addons:
  chrome: stable

language: node_js
node_js:
  - "10.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run test-headless

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build;

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
