sudo: required

addons:
  chrome: stable

language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g @angular/cli

script:
  - npm run test
  - npm run build

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
